when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        auto_refresh_proxies: true
        faker:
            locale: en_EN # set the locale
            seed: 5678 # set the random number generator seed
when@test: *dev
